version: '3.8'

services:

  api-gateway:
    build: ./api-gateway
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service
      - order-service
      - payment-service
    networks:
      - micronet

  user-service:
    build: ./user-service
    env_file:
      - .env
    ports:
      - "8085:8085"
    depends_on:
      - user-db
    networks:
      - micronet

  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: commerceManager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - micronet

  product-service:
    build: ./product-service
    ports:
      - "8084:8084"
    env_file:
      - .env
    depends_on:
      - product-db
    networks:
      - micronet

  product-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: commerceManager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - micronet

  order-service:
    build: ./order-service
    env_file:
      - .env
    depends_on:
      - order-db
    networks:
      - micronet

  order-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: commerceManager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - micronet

  payment-service:
    build: ./payment-service
    env_file:
      - .env
    depends_on:
      - payment-db
    networks:
      - micronet

  payment-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: commerceManager
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - payment-data:/var/lib/postgresql/data
    networks:
      - micronet
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    networks:
      - micronet

networks:
  micronet:
    driver: bridge

volumes:
  user-data:
  product-data:
  order-data:
  payment-data: