spring.application.name=user-service
server.port=8085
spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=commerceManager
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
