spring.application.name=order-service
server.port=8082
spring.datasource.url=jdbc:postgresql://order-db:5432/order_db
spring.datasource.username=commerceManager
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
user.service.url=http://user-service:8085
product.service.url=http://product-service:8084
payment.service.url=http://payment-service:8083